# main menu
[[main]]
name = "Things To Do"
url = "things_to_do/"
weight = 1

[[main]]
name = "Eat and Drink"
url = "#"
hasChildren = true
weight = 2

[[main]]
name = "Stay"
url = "#"
hasChildren = true
weight = 2

#[[main]]
#parent = "Articles"
#name = "Lifestyle"
#url = "articles/lifestyle/"
#weight = 2

#[[main]]
#parent = "Articles"
#name = "Cruises"
#url = "articles/cruises/"
#weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 3


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Sitemap"
url = "sitemap.xml/"
weight = 3

[[footer]]
name = "Elements"
url = "elements/"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 7

[[footer]]
name = "Terms Conditions"
url = "terms-conditions/"
weight = 8
