# main menu
[[main]]
name = "Sur Moi"
url = "about/"
weight = 1

[[main]]
name = "Articles"
url = "#"
hasChildren = true
weight = 2

[[main]]
parent = "Articles"
name = "Travel"
url = "articles/travel/"
weight = 1

[[main]]
parent = "Articles"
name = "Lifestyle"
url = "articles/lifestyle/"
weight = 2

[[main]]
parent = "Articles"
name = "Cruises"
url = "articles/cruises/"
weight = 3

[[main]]
name = "Contacter"
url = "contact/"
weight = 3


# footer menu
[[footer]]
name = "À Propos"
url = "about/"
weight = 2

[[footer]]
name = "Sitemap"
url = "sitemap.xml/"
weight = 3

[[footer]]
name = "Éléments"
url = "elements/"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 7

[[footer]]
name = "Terms Conditions"
url = "terms-conditions/"
weight = 8
