---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages (en)
- type: document
  path: exampleSite/content/english/about.md
  label: About
- type: document
  path: exampleSite/content/english/articles/_index.md
  label: Article
- type: directory
  path: exampleSite/content/english/articles
  label: All Articles
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - new-article
- type: document
  path: exampleSite/content/english/contact.md
  label: Contact
- type: heading
  label: Pages (fr)
- type: document
  path: exampleSite/content/french/about.md
  label: About
- type: document
  path: exampleSite/content/french/articles/_index.md
  label: Article
- type: directory
  path: exampleSite/content/french/articles
  label: All Articles
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - new-article
- type: document
  path: exampleSite/content/french/contact.md
  label: Contact
- type: heading
  label: Data
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content
  label: All Pages
  create: all
  match: "**/*"
  exclude: _index.md
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config/_default/config.toml
  label: Configuration
- type: document
  path: exampleSite/config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
- type: document
  path: exampleSite/config/_default/languages.toml
  label: Languages
- type: document
  path: exampleSite/config/_default/menus.en.toml
  label: Menu (en)
- type: document
  path: exampleSite/config/_default/menus.fr.toml
  label: Menu (fr)
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.81.0
