# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
primary_color = "#13AE6F"
body_color = "#fff"
text_color = "#333"
text_color_dark = "#19234C"
text_color_light = "#888"
border_color = "#ececec"
logo_color = "#082C45"
black = "#000"
white = "#fff"
light = "#F6F6F6"
dark = "#131313"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "Work Sans:wght@400;500;600;700"
primary_font_type = "sans-serif" # [serif/sans-serif/monospace]
secondary_font = "Neuton:wght@700"
secondary_font_type = "serif" # [serif/sans-serif/monospace]



############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"